export default [
    {
        id: 1,
        postedOn: '2025-12-28',
        title: 'iOS Developer',
        company: "Apple",
        type: 'Full Time', 
        experience: 'Mid Level',
        location: 'Remote',
        skills: ['SwiftUI', 'UiKit', 'Core Data'],
        job_link: 'https://www.apple.com/careers/in/',
    },
    {
        id: 2,
        postedOn: '2026-01-14',
        title: 'Frontend Developer',
        type: 'Full Time', 
        location: 'In-Office',
        experience: 'Fresher',
        company: 'Amazon',
        skills: ['Javascript', 'React', 'Tailwind CSS'],
        job_link: 'https://www.amazon.jobs/en/',
    },
    {
       id: 3,
        postedOn: '2026-01-22',
        title: 'Backend Developer',
        type: 'Full Time',
        location: 'Part Time',
        experience: 'Junior Level',
        company: 'Accenture',
        skills: ['Python', 'SQL', 'HTML', 'CSS'],
        job_link: 'https://www.accenture.com/in-en/careers/jobsearch'
    },
    {  
        id: 4,
        postedOn: '2026-02-02',
        title: 'Android Developer',
        type: 'Part Time', 
        location: 'Remote',
        experience: 'Senior Level',
        company: 'Facebook',
        skills: ['Kotlin', 'MVVM'],
        job_link: 'https://facebook.com/careers',
    },
    {
        id: 5,
        postedOn: '2026-02-25',
        title: 'Developer Advocate',
        type: 'Contract', 
        location: 'Hybrid',
        experience: 'Fresher',
        company: 'Netflix',
        skills: ['Web3', 'Content Creation', 'Community'],
        job_link: 'https://jobs.netflix.com/',
    },
];